trigger: none

pr: 
- main

resources:
 pipelines:
   - pipeline: secrui 
     source: hzzdmc.pipelines-java
     trigger:
       branches:
         include:
           - ttttt

pool:
  vmImage: ubuntu-latest

jobs:
- job: Workhzz22
  steps:
  - script: echo Hello, world44!
    displayName: 'Run a one-line script'

