# When manually running the pipeline, you can select whether it
# succeeds or fails.
parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

trigger: none


pr:
- main



pool:
  vmImage: ubuntu-latest

jobs:
- job: Work44
  steps:
  - script: echo Hello, world44!
    displayName: 'Run a one-line script'



