# When manually running the pipeline, you can select whether it
# succeeds or fails.
parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

trigger: none

pr:
- main
- ere


pool:
  vmImage: ubuntu-latest

jobs:
- job: Work2
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

- job: Work1
  steps:
  - script: echo Hello, world11!
    displayName: 'Run a one-line script'



