# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


variables:
  - group: "firstaa"
  - name: aqc
    value: bbb
  - name: qw
    value: $(qq) 

trigger: none

resources:
 pipelines:
   - pipeline: MyPipelineResource
     source: pipelines-java.git
pr: 
- main



stages:


- stage: 
  displayName: good
  jobs:
    
    - job: Work123
      pool:   
        vmImage: windows-latest
      steps:
      - script: echo $(qw)
      - script: echo ${{ variables.aqc }}
      - script: echo $[variables.qq]
      - script: echo $[variables.qw]
      - script: echo $[variables.aqc]
      - script: echo $[1+1]
      - script: echo $[{{ variables.qq }}]
        displayName: 'Run a one-line script'  
