# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pr: 
- main



stages:
- stage: 
  displayName: good

  jobs:
  - job: Work111
    pool:   
      vmImage: ubuntu-latest
    steps:
    - script: echo Hello, world44!
      displayName: 'Run a one-line script'

  - job: Work123
    pool:   
      vmImage: windows-latest
    steps:
    - script: echo Hello, world123!
      displayName: 'Run a one-line script'  
